[project]
name = "veille"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abdoulayendour", email = "abdoulaye.ndour@paps-app.com" }
]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.13",
    "httpx>=0.28.1",
    "pyyaml>=6.0.3",
]

[project.scripts]
veille = "veille:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
